#!/usr/bin/env node
/** Build a local unsigned PlugBrain NSIS candidate from current bytes only. */
import { execFileSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'
import { captureSourceState } from './source-state.mjs'

const root = join(import.meta.dirname, '..')
function resolveMakensis() {
  const envPath = process.env.PLUGBRAIN_MAKENSIS?.trim()
  if (envPath && existsSync(envPath)) return envPath

  // Common per-machine installs; anything else comes in via PLUGBRAIN_MAKENSIS
  // or PATH, so no developer's home directory is baked into the source.
  const candidates = [
    'C:\\Program Files (x86)\\NSIS\\makensis.exe',
    'C:\\Program Files\\NSIS\\makensis.exe',
  ]
  for (const c of candidates) {
    if (existsSync(c)) return c
  }

  try {
    const out = execFileSync('where', ['makensis.exe'], { encoding: 'utf8' }).trim().split(/\r?\n/)[0]
    if (out && existsSync(out)) return out
  } catch {}

  return null
}

const makensis = resolveMakensis()
const installer = join(root, 'desktop', 'PlugBrain.nsi')
// The artifact name follows package.json, so a version bump cannot leave a
// mislabelled installer behind: the release identity is written in one place.
const version = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')).version
const output = join(root, 'release', `PlugBrain-${version}-win-x64.exe`)
const ownedFiles = join(root, 'release', 'PlugBrain-owned-files.nsh')
const provenanceFile = `${output}.provenance.json`

if (process.platform !== 'win32') throw new Error('PlugBrain NSIS packaging is Windows-only')
if (process.arch !== 'x64') {
  throw new Error(`PlugBrain ${version} NSIS packaging supports win-x64 only; refusing host runtime ${process.arch}`)
}
if (!makensis) {
  throw new Error('makensis.exe not found. Set PLUGBRAIN_MAKENSIS or install NSIS.')
}
if (!existsSync(makensis)) throw new Error(`makensis does not exist: ${makensis}`)

// Capture source identity before build/package outputs can modify dist/ or
// release/.  Only generated release output is excluded from this predicate.
const source = captureSourceState(root)

execFileSync(process.execPath, [join(root, 'scripts', 'build-standalone.mjs')], { cwd: root, stdio: 'inherit' })
execFileSync(process.execPath, [join(root, 'scripts', 'verify-standalone.mjs')], { cwd: root, stdio: 'inherit' })
mkdirSync(join(root, 'release'), { recursive: true })

function walkFiles(directory) {
  const found = []
  for (const name of readdirSync(directory).sort()) {
    const full = join(directory, name)
    const stat = statSync(full)
    if (stat.isDirectory()) found.push(...walkFiles(full))
    else if (stat.isFile()) found.push(full)
    else throw new Error(`refusing non-regular release input: ${full}`)
  }
  return found
}

function nsiPath(path) {
  if (path.includes('"')) throw new Error(`refusing quote in NSIS release path: ${path}`)
  return path.replaceAll('/', '\\')
}

const distRoot = join(root, 'dist')
const distFiles = walkFiles(distRoot)
const relativeFiles = distFiles.map(file => relative(distRoot, file)).sort()
if (!relativeFiles.includes('node.exe')) throw new Error('portable node.exe is missing from the NSIS payload')
const directories = new Set(['dist', 'desktop'])
for (const file of relativeFiles) {
  const pieces = file.split(/[/\\]/)
  pieces.pop()
  while (pieces.length > 0) {
    directories.add(join('dist', ...pieces))
    pieces.pop()
  }
}
const deleteLines = [
  '; generated by scripts/package-nsis.mjs - do not hand-edit',
  // node.exe is deleted and verified separately before any other payload path.
  ...relativeFiles.filter(file => file !== 'node.exe').map(file => `Delete "$INSTDIR\\dist\\${nsiPath(file)}"`),
  'Delete "$INSTDIR\\desktop\\launch.cmd"',
  'Delete "$INSTDIR\\desktop\\autostart.vbs"',
  'Delete "$INSTDIR\\bin\\plugbrain.cmd"',
  'Delete "$INSTDIR\\README.md"',
  ...[...directories]
    .sort((a, b) => b.split(/[/\\]/).length - a.split(/[/\\]/).length || b.localeCompare(a))
    .map(directory => `RMDir "$INSTDIR\\${nsiPath(directory)}"`),
]
writeFileSync(ownedFiles, `${deleteLines.join('\n')}\n`, 'utf8')
execFileSync(makensis, [installer], { cwd: root, stdio: 'inherit' })

if (!existsSync(output)) throw new Error(`NSIS did not produce ${output}`)
const sha256 = createHash('sha256').update(readFileSync(output)).digest('hex')
writeFileSync(`${output}.sha256`, `${sha256}  ${output.split(/[\\/]/).pop()}\n`, 'utf8')
const standaloneManifest = join(root, 'dist', 'release.json')
if (!existsSync(standaloneManifest)) throw new Error('standalone release manifest is missing after package build')
writeFileSync(provenanceFile, `${JSON.stringify({
  schemaVersion: 1,
  schema: 1,
  product: 'PlugBrain',
  artifactName: output.split(/[\\/]/).pop(),
  candidate: output.split(/[\\/]/).pop(),
  sha256,
  bytes: statSync(output).size,
  head: source.head,
  dirty: source.dirty,
  generatedOutputExcluded: source.generatedOutputExcluded,
  dirtyPorcelainSha256: source.dirtyPorcelainSha256,
  source,
  standaloneManifest: {
    path: 'dist/release.json',
    sha256: createHash('sha256').update(readFileSync(standaloneManifest)).digest('hex'),
  },
  signature: { type: 'none', status: 'UNSIGNED_NOT_FOR_PUBLIC_RELEASE' },
}, null, 2)}\n`, 'utf8')
console.log(`PlugBrain NSIS candidate: ${output}\nSHA-256: ${sha256}`)
