#!/usr/bin/env node
/** Build a local unsigned PlugBrain NSIS candidate from current bytes only. */
import { execFileSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'

const root = join(import.meta.dirname, '..')
const makensis = process.env.PLUGBRAIN_MAKENSIS?.trim()
const installer = join(root, 'desktop', 'PlugBrain.nsi')
const output = join(root, 'release', 'PlugBrain-0.1.0-win-x64.exe')
const ownedFiles = join(root, 'release', 'PlugBrain-owned-files.nsh')

if (process.platform !== 'win32') throw new Error('PlugBrain NSIS packaging is Windows-only')
if (process.arch !== 'x64') {
  throw new Error(`PlugBrain 0.1.0 NSIS packaging supports win-x64 only; refusing host runtime ${process.arch}`)
}
if (!makensis) {
  throw new Error('PLUGBRAIN_MAKENSIS must name the explicitly selected makensis.exe')
}
if (!existsSync(makensis)) throw new Error(`PLUGBRAIN_MAKENSIS does not exist: ${makensis}`)

execFileSync(process.execPath, [join(root, 'scripts', 'build-standalone.mjs')], { cwd: root, stdio: 'inherit' })
execFileSync(process.execPath, [join(root, 'scripts', 'verify-standalone.mjs')], { cwd: root, stdio: 'inherit' })
mkdirSync(join(root, 'release'), { recursive: true })

function walkFiles(directory) {
  const found = []
  for (const name of readdirSync(directory).sort()) {
    const full = join(directory, name)
    const stat = statSync(full)
    if (stat.isDirectory()) found.push(...walkFiles(full))
    else if (stat.isFile()) found.push(full)
    else throw new Error(`refusing non-regular release input: ${full}`)
  }
  return found
}

function nsiPath(path) {
  if (path.includes('"')) throw new Error(`refusing quote in NSIS release path: ${path}`)
  return path.replaceAll('/', '\\')
}

const distRoot = join(root, 'dist')
const distFiles = walkFiles(distRoot)
const relativeFiles = distFiles.map(file => relative(distRoot, file)).sort()
if (!relativeFiles.includes('node.exe')) throw new Error('portable node.exe is missing from the NSIS payload')
const directories = new Set(['dist', 'desktop'])
for (const file of relativeFiles) {
  const pieces = file.split(/[/\\]/)
  pieces.pop()
  while (pieces.length > 0) {
    directories.add(join('dist', ...pieces))
    pieces.pop()
  }
}
const deleteLines = [
  '; generated by scripts/package-nsis.mjs - do not hand-edit',
  // node.exe is deleted and verified separately before any other payload path.
  ...relativeFiles.filter(file => file !== 'node.exe').map(file => `Delete "$INSTDIR\\dist\\${nsiPath(file)}"`),
  'Delete "$INSTDIR\\desktop\\launch.cmd"',
  'Delete "$INSTDIR\\README.md"',
  ...[...directories]
    .sort((a, b) => b.split(/[/\\]/).length - a.split(/[/\\]/).length || b.localeCompare(a))
    .map(directory => `RMDir "$INSTDIR\\${nsiPath(directory)}"`),
]
writeFileSync(ownedFiles, `${deleteLines.join('\n')}\n`, 'utf8')
execFileSync(makensis, [installer], { cwd: root, stdio: 'inherit' })

if (!existsSync(output)) throw new Error(`NSIS did not produce ${output}`)
const sha256 = createHash('sha256').update(readFileSync(output)).digest('hex')
writeFileSync(`${output}.sha256`, `${sha256}  ${output.split(/[\\/]/).pop()}\n`, 'utf8')
console.log(`PlugBrain NSIS candidate: ${output}\nSHA-256: ${sha256}`)
